---

build:
    - MANIFEST.in
    - Dockerfile
    - .dockerignore
    - scripts/**
docs:
    - docs/**
    - README.md
    - AUTHORS.md
    - CONTRIBUTING.md
    - CHANGELOG.md
src:
    - commit_lint/**
    - pyproject.toml
tests:
    - tests/**
